/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pooltable.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { useEffect } from 'react'



export default function Pooltable(props) {
  const { nodes, materials } = useGLTF('/pooltable.glb')

  useEffect(() => {
  if (props.onLoaded && typeof props.onLoaded === 'function') {
    // Wait a bit before reporting loaded to make sure material and geometry are ready
    const timer = setTimeout(() => {
      props.onLoaded();
    }, 200);
    return () => clearTimeout(timer);
  }
}, [props.onLoaded]);
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <RigidBody
          friction={1}
          restitution={0}
          type='fixed'
          colliders={'trimesh'}
          userData={{ isHole: true, name: 'hole' }}
        >
          <mesh geometry={nodes.Mesh001.geometry} material={materials['billard.001']} />
        </RigidBody>
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['bordure.001']} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials['pied.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/pooltable.glb')
