/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pooltable.glb 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useTrimesh, Debug } from '@react-three/cannon'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pooltable.glb')
  const [greenRef] = useTrimesh(
    () => ({
      args: [
        nodes.Cube001_1.geometry.attributes.position.array,
        nodes.Cube001_1.geometry.index.array,
      ],
      mass: 0,
      material:'green',
    }),
    useRef()
  )
  const [woodRef] = useTrimesh(
    () => ({
      args: [
        nodes.Cube001.geometry.attributes.position.array,
        nodes.Cube001.geometry.index.array,
      ],
      mass: 0,
      position: [0, 0, 0],
    }),
    useRef()
  )
  const [pocketRef] = useTrimesh(
    () => ({
      args: [
        nodes.Cube001_2.geometry.attributes.position.array,
        nodes.Cube001_2.geometry.index.array,
      ],
      mass: 0,
    }),
    useRef()
  )
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.wood} ref={woodRef} receiveShadow/>
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['green.001']} ref={greenRef} receiveShadow/>
      <mesh geometry={nodes.Cube001_2.geometry} material={materials.pocket}   receiveShadow />
    </group>
  )
}

useGLTF.preload('/pooltable.glb')


