/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pooltable.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'


export default function Model(props) {
  const { nodes, materials } = useGLTF('/pooltable.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.05}>
        <RigidBody
          friction={1}
          restitution={0}
          type='fixed'
          colliders={'trimesh'}
          userData={{ isHole: true, name: 'hole' }}
        >
          <mesh geometry={nodes.Mesh001.geometry} material={materials['billard.001']} />
        </RigidBody>
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['bordure.001']} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials['pied.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/pooltable.glb')
